################## Filebeat Pulpo Connector DE Configuration ##################

# This file is the configuration file for the filebeat running inside this
# beanstalk docker instance

#==========================  Modules configuration ============================

filebeat.prospectors:

#------------------------------ Log prospector --------------------------------
- input_type: json
  paths:
    - /var/log/aws/containers/*/*.log
  fields_under_root: true

- input_type: log
  paths:
    - /var/log/aws/*.log
    - /var/log/aws/containers/*.log
    - /var/log/aws/containers/*/*.log

  multiline.pattern: '^[[:space:]]+|^Caused by:'
  multiline.negate: false
  multiline.match: after

#================================ General ======================================

tags: '${PULPO_FILEBEAT_TAGS}'

fields:
  env: '${PULPO_FILEBEAT_ENV}'
  service: '${PULPO_FILEBEAT_SERVICE}'

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: '${PULPO_FILEBEAT_ES_HOSTS}'

output.console:
  enabled: false

#================================ Logging ======================================
logging.level: info

logging.to_files: true

logging.to_syslog: false

logging.files:
  keepfiles: 5

#================================ Processors ===================================

processors:
  - add_cloud_metadata:
